real horas,valor_hora,salario
caracter siga

inicio
    siga <- 'S'
    
    mientras(siga = 'S') o (siga = 's') haga
    
        escriba "Horas trabajadas"
        lea horas
        
        escriba "Valor por hora"
        lea valor_hora
        
        salario <- horas * valor_hora
        
        escriba "Salario: ",salario

        llamar nueva_linea

        escriba "Desea ingresar otro trabajador (S/N)"
        lea siga
        
    fin mientras
fin
